version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis-data:/data
    networks:
      - apps

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DB: ${MONGO_DB}
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb:/data/db
    networks:
      - apps

networks:
  apps: